<!-- <div id="font-family">
            <button id="Arial" data-font="Arial" data-name="Arial" style="font-family:Arial;">
            <div class="content">
             <p>    Arial </p>
                </div>
            </button>
            <button id="Times New Roman" data-font="Times New Roman" data-name="Times New Roman" style="font-family:'Times New Roman';">
            <div class="content">
            <p>  Times New Roman </p>
                </div>
            </button>
             
        </div> -->

<div class="fonts-family-area" id="custom-font-family">
     <span id="LiAlinurShishir" data-font="LiAlinurShishir" data-name="Alinur Shishir"><div class="content" style="font-family: LiAlinurShishir;"> <p> আমার সোনার বাংলা </p> </div></span>
     <span id="LiAlinurAkorshon" data-font="LiAlinurAkorshon" data-name="Alinur Akorshon"><div class="content" style="font-family: LiAlinurAkorshon;"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiSweetShreyamUnicode" data-font="LiSweetShreyamUnicode" data-name="Li Sweet Shreyam"><div class="content" style="font-family: LiSweetShreyamUnicode;"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="PotroSansBanglaRegular" data-font="PotroSansBanglaRegular" data-name="PotroSansBangla-Regular"><div class="content" style="font-family: PotroSansBanglaRegular;"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiShohidAbuSayedUnicode" data-font="LiShohidAbuSayedUnicode" data-name="Li Shohid Abu Sayed Unicode"><div class="content" style="font-family: LiShohidAbuSayedUnicode;"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiAlinurNakkhatraUnicode" data-font="LiAlinurNakkhatraUnicode" data-name="Li Alinur Nakkhatra Unicode"><div class="content" style="font-family: LiAlinurNakkhatraUnicode;"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiSweetRupamUnicode" data-font="LiSweetRupamUnicode" data-name="Li Sweet Rupam Unicode"><div class="content" style="font-family: LiSweetRupamUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiAlinurUllasUnicode" data-font="LiAlinurUllasUnicode" data-name="Li Alinur Ullas Unicode"><div class="content" style="font-family: LiAlinurUllasUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiHalderChinmoyeeUnicode" data-font="LiHalderChinmoyeeUnicode" data-name="Li Halder Chinmoyee Unicode"><div class="content" style="font-family: LiHalderChinmoyeeUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiAlinurKuyashaUnicode" data-font="LiAlinurKuyashaUnicode" data-name="Li Alinur Kuyasha Unicode"><div class="content" style="font-family: LiAlinurKuyashaUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiAlinurBahubrihiUnicode" data-font="LiAlinurBahubrihiUnicode" data-name="Li Alinur Bahubrihi Unicode"><div class="content" style="font-family: LiAlinurBahubrihiUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiAlinurAkorshonUnicode" data-font="LiAlinurAkorshonUnicode" data-name="Li Alinur Akorshon Unicode"><div class="content" style="font-family: LiAlinurAkorshonUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiAlinurBanglabornoUnicode" data-font="LiAlinurBanglabornoUnicode" data-name="Li Alinur Banglaborno Unicode"><div class="content" style="font-family: LiAlinurBanglabornoUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                   
     <span id="LiAlinurProhorUnicode" data-font="LiAlinurProhorUnicode" data-name="Li Alinur Prohor Unicode"><div class="content" style="font-family: LiAlinurProhorUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurTatsamaUnicode" data-font="LiAlinurTatsamaUnicode" data-name="Li Alinur Tatsama Unicode"><div class="content" style="font-family: LiAlinurTatsamaUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurSangbadpatraUnicode" data-font="LiAlinurSangbadpatraUnicode" data-name="Li Alinur Sangbadpatra Unicode"><div class="content" style="font-family: LiAlinurSangbadpatraUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurRuposhiUnicode" data-font="LiAlinurSangbadpatraUnicode" data-name="Li Alinur Ruposhi Unicode"><div class="content" style="font-family: LiAlinurRuposhiUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiSweetShreyamUnicode" data-font="LiSweetShreyamUnicode" data-name="Li Sweet Shreyam Unicode"><div class="content" style="font-family: LiSweetShreyamUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiSweetRupamUnicode" data-font="LiSweetRupamUnicode" data-name="Li Sweet Shreyam Unicode"><div class="content" style="font-family: LiSweetRupamUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiSabbirAshalota3Unicode" data-font="LiSabbirAshalota3Unicode" data-name="Li Sabbir Ashalota 3 Unicode"><div class="content" style="font-family: LiSabbirAshalota3Unicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiMahfuzHimadriUnicode" data-font="LiMahfuzHimadriUnicode" data-name="Li Mahfuz Himadri Unicode"><div class="content" style="font-family: LiMahfuzHimadriUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiManowarNiharUnicode" data-font="LiManowarNiharUnicode" data-name="Li Manowar Nihar Unicode"><div class="content" style="font-family: LiManowarNiharUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiSirajeeSanjarUnicode" data-font="LiSirajeeSanjarUnicode" data-name="Li Sirajee Sanjar Unicode"><div class="content" style="font-family: LiSirajeeSanjarUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurSmaroklipiUnicode" data-font="LiAlinurSmaroklipiUnicode" data-name="Li Alinur Smaroklipi Unicode"><div class="content" style="font-family: LiAlinurSmaroklipiUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiSKBishalUnicode" data-font="LiSKBishalUnicode" data-name="Li SK Bishal Unicode"><div class="content" style="font-family: LiSKBishalUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurRangpurUnicode" data-font="LiAlinurRangpurUnicode" data-name="Li Alinur Rangpur Unicode"><div class="content" style="font-family: LiAlinurRangpurUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiDurbinitoUnicode" data-font="LiDurbinitoUnicode" data-name="Li Durbinito Unicode"><div class="content" style="font-family: LiDurbinitoUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiHalderSourikUnicode" data-font="LiHalderSourikUnicode" data-name="Li Halder Sourik Unicode"><div class="content" style="font-family: LiHalderSourikUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiSuparnaUnicode" data-font="LiSuparnaUnicode" data-name="Li Suparna Unicode"><div class="content" style="font-family: LiSuparnaUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurAtithiUnicode" data-font="LiAlinurAtithiUnicode" data-name="Li Alinur Atithi Unicode"><div class="content" style="font-family: LiAlinurAtithiUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiManowarMurshidabadUnicode" data-font="LiManowarMurshidabadUnicode" data-name="Li Manowar Murshidabad Unicode"><div class="content" style="font-family: LiManowarMurshidabadUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurImaratUnicode" data-font="LiAlinurImaratUnicode" data-name="Li Alinur Imarat Unicode"><div class="content" style="font-family: LiAlinurImaratUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurSnigdhaUnicode" data-font="LiAlinurSnigdhaUnicode" data-name="Li Alinur Snigdha Unicode"><div class="content" style="font-family: LiAlinurSnigdhaUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiFazlayMunnishaMattraUnicodeMattra" data-font="LiFazlayMunnishaMattraUnicodeMattra" data-name="Li Fazlay Munnisha Mattra Unicode Mattra"><div class="content" style="font-family: LiFazlayMunnishaMattraUnicodeMattra"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiNahidaBornomalaUnicode" data-font="LiNahidaBornomalaUnicode" data-name="Li Nahida Bornomala Unicode"><div class="content" style="font-family: LiNahidaBornomalaUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiSuparnaUnicode1" data-font="LiSuparnaUnicode1" data-name="Li Suparna Unicode"><div class="content" style="font-family: LiSuparnaUnicode1"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurAdorUnicode" data-font="LiAlinurAdorUnicode" data-name="Li Alinur Ador Unicode"><div class="content" style="font-family: LiAlinurAdorUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiByomgraphyKoushaliUnicode" data-font="LiByomgraphyKoushaliUnicode" data-name="Li Byomgraphy Koushali Unicode"><div class="content" style="font-family: LiByomgraphyKoushaliUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurProttyoeeUnicode" data-font="LiAlinurProttyoeeUnicode" data-name="Li Alinur Prottyoee Unicode"><div class="content" style="font-family: LiAlinurProttyoeeUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurBornoBikashUnicode" data-font="LiAlinurBornoBikashUnicode" data-name="Li Alinur BornoBikash Unicode"><div class="content" style="font-family: LiAlinurBornoBikashUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiManowarMatribhumiUnicode" data-font="LiManowarMatribhumiUnicode" data-name="Li Manowar Matribhumi Unicode"><div class="content" style="font-family: LiManowarMatribhumiUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurKurigramUnicode" data-font="LiAlinurKurigramUnicode" data-name="Li Alinur Kurigram Unicode"><div class="content" style="font-family: LiAlinurKurigramUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiLiakatTanjinaUnicodeRegular" data-font="LiLiakatTanjinaUnicodeRegular" data-name="Li Liakat Tanjina Unicode Regular "><div class="content" style="font-family: LiLiakatTanjinaUnicodeRegular"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiPadmasetuUnicode" data-font="LiPadmasetuUnicode" data-name="Li Padmasetu Unicode"><div class="content" style="font-family: LiPadmasetuUnicode"> <p> আমার সোনার বাংলা </p> </div></span>                                                
     <span id="LiAlinurDristantoUnicode-Regular" data-font="LiAlinurDristantoUnicode-Regular" data-name="LiAlinurDristantoUnicode-Regular"><div class="content" style="font-family: LiAlinurDristantoUnicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <!-- end of page Five -->
     <span id="LiMainakBuniyadiUnicode" data-font="LiMainakBuniyadiUnicode" data-name="Li Mainak Buniyadi Unicode"><div class="content" style="font-family: LiMainakBuniyadiUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurProjapotiUnicode" data-font="LiAlinurProjapotiUnicode" data-name="Li Alinur Projapoti Unicode"><div class="content" style="font-family: LiAlinurProjapotiUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiManowarFingeUnicode" data-font="LiManowarFingeUnicode" data-name="Li Manowar Finge Unicode"><div class="content" style="font-family: LiManowarFingeUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiPriyashaBharotUnicode" data-font="LiPriyashaBharotUnicode" data-name="Li Priyasha Bharot Unicode"><div class="content" style="font-family: LiPriyashaBharotUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurShowpnocari" data-font="LiAlinurShowpnocari" data-name="Li Alinur Showpnocari"><div class="content" style="font-family: LiAlinurShowpnocari"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiLiakatTawhidUnicode" data-font="LiLiakatTawhidUnicode" data-name="Li Liakat Tawhid Unicode"><div class="content" style="font-family: LiLiakatTawhidUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiParadoxicalSajidUnicode" data-font="LiParadoxicalSajidUnicode" data-name="Li Paradoxical Sajid Unicode"><div class="content" style="font-family: LiParadoxicalSajidUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurIchamatiUnicode" data-font="LiAlinurIchamatiUnicode" data-name="Li Alinur Ichamati Unicode"><div class="content" style="font-family: LiAlinurIchamatiUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurAbakasUnicode" data-font="LiAlinurAbakasUnicode" data-name="Li Alinur Abakas Unicode"><div class="content" style="font-family: LiAlinurAbakasUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiHasanIccheghuriUnicode-Regular" data-font="LiHasanIccheghuriUnicode-Regular" data-name="LiHasanIccheghuriUnicode-Regular"><div class="content" style="font-family: LiHasanIccheghuriUnicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAdorNoirritSemiBold" data-font="LiAdorNoirritSemiBold" data-name="Li Ador Noirrit SemiBold"><div class="content" style="font-family: LiAdorNoirritSemiBold"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurBoisakhUnicode-Regular" data-font="LiAdorNoirritSemiBold" data-name="LiAlinurBoisakhUnicode-Regular"><div class="content" style="font-family: LiAlinurBoisakhUnicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiShamimCholontikaOld-Regular" data-font="LiShamimCholontikaOld-Regular" data-name="LiShamimCholontikaOld-Regular"><div class="content" style="font-family: LiShamimCholontikaOld-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiShamimCholontikaOld-Regular" data-font="LiShamimCholontikaOld-Regular" data-name="LiShamimCholontikaOld-Regular"><div class="content" style="font-family: LiShamimCholontikaOld-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiShadhinata2Unicode-Regular" data-font="LiShadhinata2Unicode-Regular" data-name="LiShadhinata2Unicode-Regular"><div class="content" style="font-family: LiShadhinata2Unicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiHimaloyUnicode-Regular" data-font="LiHimaloyUnicode-Regular" data-name="LiHimaloyUnicode-Regular"><div class="content" style="font-family: LiHimaloyUnicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <!-- ===============page seven swadhinota======                                          -->
     <span id="LiPadmaragUnicode-Regular" data-font="LiPadmaragUnicode-Regular" data-name="LiPadmaragUnicode-Regular"><div class="content" style="font-family: LiPadmaragUnicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAdorTrikonomitiUnicode-Regular" data-font="LiAdorTrikonomitiUnicode-Regular" data-name="LiAdorTrikonomitiUnicode-Regular"><div class="content" style="font-family: LiAdorTrikonomitiUnicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAdorTrikonomitiUnicode-Regular" data-font="LiAdorTrikonomitiUnicode-Regular" data-name="LiAdorTrikonomitiUnicode-Regular"><div class="content" style="font-family: LiAdorTrikonomitiUnicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiBhasa52Unicode-Regular" data-font="LiBhasa52Unicode-Regular" data-name="LiBhasa52Unicode-Regular"><div class="content" style="font-family: LiBhasa52Unicode-Regular"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurHastasailiUnicode" data-font="LiAlinurHastasailiUnicode" data-name="Li Alinur Hastasaili Unicode"><div class="content" style="font-family: LiAlinurHastasailiUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurBashundharaUnicode" data-font="LiAlinurBashundharaUnicode" data-name="Li Alinur Bashundhara Unicode"><div class="content" style="font-family: LiAlinurBashundharaUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiSRFChuadangaUnicode" data-font="LiSRFChuadangaUnicode" data-name="Li SRF Chuadanga Unicode"><div class="content" style="font-family: LiSRFChuadangaUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiMAKAkhlimaUnicode" data-font="LiMAKAkhlimaUnicode" data-name="Li MAK Akhlima Unicode"><div class="content" style="font-family: LiMAKAkhlimaUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiHasanJolchobiUnicode" data-font="LiHasanJolchobiUnicode" data-name="Li Hasan Jolchobi Unicode"><div class="content" style="font-family: LiHasanJolchobiUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurKathakaliUnicode" data-font="LiAlinurKathakaliUnicode" data-name="Li Alinur Kathakali Unicode"><div class="content" style="font-family: LiAlinurKathakaliUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiAlinurDeyalikaUnicode" data-font="LiAlinurDeyalikaUnicode" data-name="Li Alinur Deyalika Unicode"><div class="content" style="font-family: LiAlinurDeyalikaUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <span id="LiUtsabBanglaUnicode" data-font="LiUtsabBanglaUnicode" data-name="Li Utsab Bangla Unicode"><div class="content" style="font-family: LiUtsabBanglaUnicode"> <p> আমার সোনার বাংলা </p> </div></span> 
     <!-- =====emd of the page eight======== -->



</div>